export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS"
export const AUTHENTICATED_FAILED = "AUTHENTICATED_FAILED"
export const LOGOUT = "LOGOUT"